// Auto-generated: registers ALL components as beta-*
import './card/card.js';  // beta-card (Tier 3 extended)
import './alert/alert.js';  // beta-alert
import './animated-image/animated-image.js';  // beta-animated-image
import './animation/animation.js';  // beta-animation
import './avatar/avatar.js';  // beta-avatar
import './badge/badge.js';  // beta-badge
import './breadcrumb/breadcrumb.js';  // beta-breadcrumb
import './breadcrumb-item/breadcrumb-item.js';  // beta-breadcrumb-item
import './button/button.js';  // beta-button
import './button-group/button-group.js';  // beta-button-group
import './carousel/carousel.js';  // beta-carousel
import './carousel-item/carousel-item.js';  // beta-carousel-item
import './checkbox/checkbox.js';  // beta-checkbox
import './color-picker/color-picker.js';  // beta-color-picker
import './copy-button/copy-button.js';  // beta-copy-button
import './details/details.js';  // beta-details
import './dialog/dialog.js';  // beta-dialog
import './divider/divider.js';  // beta-divider
import './drawer/drawer.js';  // beta-drawer
import './dropdown/dropdown.js';  // beta-dropdown
import './format-bytes/format-bytes.js';  // beta-format-bytes
import './format-date/format-date.js';  // beta-format-date
import './format-number/format-number.js';  // beta-format-number
import './icon/icon.js';  // beta-icon
import './icon-button/icon-button.js';  // beta-icon-button
import './image-comparer/image-comparer.js';  // beta-image-comparer
import './include/include.js';  // beta-include
import './input/input.js';  // beta-input
import './menu/menu.js';  // beta-menu
import './menu-item/menu-item.js';  // beta-menu-item
import './menu-label/menu-label.js';  // beta-menu-label
import './mutation-observer/mutation-observer.js';  // beta-mutation-observer
import './option/option.js';  // beta-option
import './popup/popup.js';  // beta-popup
import './progress-bar/progress-bar.js';  // beta-progress-bar
import './progress-ring/progress-ring.js';  // beta-progress-ring
import './qr-code/qr-code.js';  // beta-qr-code
import './radio/radio.js';  // beta-radio
import './radio-button/radio-button.js';  // beta-radio-button
import './radio-group/radio-group.js';  // beta-radio-group
import './range/range.js';  // beta-range
import './rating/rating.js';  // beta-rating
import './relative-time/relative-time.js';  // beta-relative-time
import './resize-observer/resize-observer.js';  // beta-resize-observer
import './select/select.js';  // beta-select
import './skeleton/skeleton.js';  // beta-skeleton
import './spinner/spinner.js';  // beta-spinner
import './split-panel/split-panel.js';  // beta-split-panel
import './switch/switch.js';  // beta-switch
import './tab/tab.js';  // beta-tab
import './tab-group/tab-group.js';  // beta-tab-group
import './tab-panel/tab-panel.js';  // beta-tab-panel
import './tag/tag.js';  // beta-tag
import './textarea/textarea.js';  // beta-textarea
import './tooltip/tooltip.js';  // beta-tooltip
import './tree/tree.js';  // beta-tree
import './tree-item/tree-item.js';  // beta-tree-item
import './visually-hidden/visually-hidden.js';  // beta-visually-hidden
